version: '2'
services:
    baseapp-app:
        image: baseapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://baseapp-mysql:3306/baseapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    baseapp-mysql:
        extends:
            file: mysql.yml
            service: baseapp-mysql
